#loading CSV files
Fast_Pass <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/Fast_Pass.csv')
FPGr3FDP <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr3FDP.csv')
FPGr3Geometry <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr3Geometry.csv')
FPGr3Money <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr3Money.csv')
FPGr3Mult <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr3Mult.csv')
FPGr3Round <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr3Round.csv')
FPGr3Time <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr3Time.csv')
FPGr4FDP <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr4FDP.csv')
FPGr4Geometry <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr4Geometry.csv')
FPGr4Money <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr4Money.csv')
FPGr4Mult <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr4Mult.csv')
FPGr4Round <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr4Round.csv')
FPGr4Time <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr4Time.csv')
FPGr5FDP <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr5FDP.csv')
FPGr5Geometry <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr5Geometry.csv')
FPGr5Money <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr5Money.csv')
FPGr5Mult <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr5Mult.csv')
FPGr5Round <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr5Round.csv')
FPGr5Time <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr5Time.csv')
Wheel_Questions <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/Wheel_Questions.csv')
 print(FPGr3FDP[4], )