#loading CSV files
FastPass <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FastPass.csv')
FPGr3Geometry <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr3Geometry.csv')
FPGr3Money <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr3Money.csv')
FPGr3Mult <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr3Mult.csv')
FPGr3Round <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr3Round.csv')
FPGr3Time <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr3Time.csv')
FPGr4Time <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr4Time.csv')
FPGr5Time <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FPGr5Time.csv')
FRGr3FDP <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FRGr3FDP.csv')
FRGr4FDP <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FRGr4FDP.csv')
FRGr4Geometry <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FRGr4Geometry.csv')
FRGr4Money <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FRGr4Money.csv')
FRGr4Mult <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FRGr4Mult.csv')
FRGr4Round <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FRGr4Round.csv')
FRGr5FDP <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FRGr5FDP.csv')
FRGr5Geometry <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FRGr5Geometry.csv')
FRGr5Money <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FRGr5Money.csv')
FRGr5Mult <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FRGr5Mult.csv')
FRGr5Round <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/FRGr5Round.csv')
Wheel_Questions <- read.csv(file = 'C:/Dev/ShiroBots/r_code/command_code/Wheel_Questions.csv')
source("C:/Dev/ShiroBots/r_code/command_code/imports/FastPassV1.R")
FastPassQuest(2, 4)